### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by jonathonmcclen** [learn-co-curriculum/getting-remote-data-working-with-apis#1]
### Canvas Link

https://learning.flatironschool.com/courses/1879/pages/working-with-apis?module_item_id=259184

### Concern

In the section titled " Finding and api endpoint the fourth paragraph starts "The page brings you **to is** the desired set of data!" 

Something like "The page brings you to **a** desired set of data" or " the url brings you the **THE** desired set of data!" would fix this grammar issue

### Suggested Changes

Something like "The page brings you to **a** desired set of data" or " the url brings you the **THE** desired set of data!" would fix this grammar issue

**Comment by ihollander** [comment]
Thanks @jonathonmcclen! We'll get this corrected shortly.
